### ISSUE TITLE
Routing Errorの解決

### ISSUE THREAD

**Issue by Kotaro18** [Kotaro18/footomo#3]
これまでは"いいね"ができていたが、
急にできなくなった。
<img width="1440" alt="Routing Error" src="https://user-images.githubusercontent.com/56097471/119746857-61e5fb80-becc-11eb-9bb8-0c7aefea37ed.png">

Routing Errorで調べて、
自分が作成したルートも問題なさそうです。
<img width="1440" alt="ルートはある" src="https://user-images.githubusercontent.com/56097471/119746906-85a94180-becc-11eb-92d0-495c9152f963.png">

index.html.erb
```rails:index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>    

        </div>
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <%# .url(:medium)としてあげることで、mediumで指定したサイズにリサイズできる。 %>
        <% end %>

        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
              <%# 投稿に、サインインしているユーザーのいいねが、あるかどうかを判断する。 %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
            <%# <%= link_to "", "#", class: "love" %>
            <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <%# <div><strong>「いいね！」10件</strong></div> %>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
            
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
```

route.rb
```ruby:route.rb
Rails.application.routes.draw do
  devise_for :users, # ここの行にカンマを追加
    controllers: { registrations: 'registrations' } # ここの行を追加

  root 'posts#index'
  # postsコントローラーのindexアクションを処理する。

  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only: %i(new create index show destroy) do
    # resourcesを追加するだけで、各ページへのルートが作成される。
    resources :photos, only: %i(create)

    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  # photosをネスト(入れ子)にすることで、postsと親子関係を紐づけられる。
end
```

likes_controller.rb
```ruby:likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!
  # サインイン済みユーザーのみに、アクセス許可を与えている。

  def create
    @like = current_user.likes.build(like_params)
    # buildメソッドを使って、インスタンスを作成する。
    @post = @like.post
    # postメソッドはgetメソッドと同じこと役割で、情報を取得する際に使う。
    # ここでは、@likeに紐づく、post_id(いいねを押した投稿のid)とuser_id(現在サインインしているユーザーのid)の情報を取得する。
    # @postは、どの投稿にいいねを押したかを判断するために、ビュー作成時に使用する。
    if @like.save
      respond_to :js
      # respond_toは、返却するレスポンスのフォーマットを切り替えるためのメソッド
      # 今回いいねを押したら、リアルタイムでビューを反映させるために、JS形式でレスポンスを返す様にしている。
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    # 受け取ったHTTPリクエストから、idを判別し、指定のレコード1つを@likeに代入している。
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
      # paramsは送られてきたリクエスト情報をひとまとめにする。
      # permitは変更を加えられるキーを指定する。今回の場合は、post_id
      # つまり、いいねを押した時に、どの投稿をいいねしたのかpost_id(キー)の情報(バリュー)を変更する。
    end
end
```

like.rb
```ruby:like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
  # uniquenessは重複していないことを検証する。
  # ここでは、user_idとpost_idが重複していないことを検証する。
end
```

どちらに原因があるのでしょうか。

**Comment by Kotaro18** [comment]
GETとPOSTの違いについて理解できていなかったので、調べてみました。

https://blog.senseshare.jp/get-post-method.html
こちらでは、GETはページ番号などをパラメーターで表示したい時に使用し、POSTは個人情報などを入力する時に使用するとありました。
また、GETは「ページの取得」で、POSTは「情報の送信」のためのリクエストと理解できました。

その上で、コードを確認してみました。
まず、route.rbではlikesのcreateアクションが定義されており、
route.rb
```ruby:route.rb
Rails.application.routes.draw do
  devise_for :users, # ここの行にカンマを追加
    controllers: { registrations: 'registrations' } # ここの行を追加

  root 'posts#index'
  # postsコントローラーのindexアクションを処理する。

  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only: %i(new create index show destroy) do
    # resourcesを追加するだけで、各ページへのルートが作成される。
    resources :photos, only: %i(create)

    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  # photosをネスト(入れ子)にすることで、postsと親子関係を紐づけられる。
end
```

likes_controller.rbでは、postメソットが設定されていると思います。
likes_controller.rb
```ruby:likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!
  # サインイン済みユーザーのみに、アクセス許可を与えている。

  def create
    @like = current_user.likes.build(like_params)
    # buildメソッドを使って、インスタンスを作成する。
    @post = @like.post
    # postメソッドはgetメソッドと同じこと役割で、情報を取得する際に使う。
    # ここでは、@likeに紐づく、post_id(いいねを押した投稿のid)とuser_id(現在サインインしているユーザーのid)の情報を取得する。
    # @postは、どの投稿にいいねを押したかを判断するために、ビュー作成時に使用する。
    if @like.save
      respond_to :js
      # respond_toは、返却するレスポンスのフォーマットを切り替えるためのメソッド
      # 今回いいねを押したら、リアルタイムでビューを反映させるために、JS形式でレスポンスを返す様にしている。
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    # 受け取ったHTTPリクエストから、idを判別し、指定のレコード1つを@likeに代入している。
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
      # paramsは送られてきたリクエスト情報をひとまとめにする。
      # permitは変更を加えられるキーを指定する。今回の場合は、post_id
      # つまり、いいねを押した時に、どの投稿をいいねしたのかpost_id(キー)の情報(バリュー)を変更する。
    end
end
```

index.html.erbでも、いいねの取得にはpostを要求しています。
それなのに何故、[GET]のRouting Errorが表示されるのでしょうか。

**Comment by masayuki14** [comment]
Viewでの指定箇所はこのあたりだと思います。

https://github.com/Kotaro18/footomo/blob/3efbc6f13304c8dd05747982c1bf7272dc09887b/app/views/posts/show.html.erb#L40
https://github.com/Kotaro18/footomo/blob/3efbc6f13304c8dd05747982c1bf7272dc09887b/app/views/posts/index.html.erb#L35


`method: :POST` となっていますね。

ドキュメントとをみると

> HTTPメソッド(:post, :delete, :patch, :put)の指定
https://railsdoc.com/page/link_to

となっており、小文字での指定です。


ソースコードでも小文字で判定しているので、こちらが原因だと思います。

https://github.com/rails/rails/blob/f33d52c95217212cbacc8d5e44b5a8e3cdc6f5b3/actionview/lib/action_view/helpers/url_helper.rb#L310-L325

**Comment by Kotaro18** [comment]
ご確認有難うございます。
postを小文字にしてみましたが、またGETエラーが出てしまいました。

index.html.erb
```ruby:index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>    

        </div>
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <%# .url(:medium)としてあげることで、mediumで指定したサイズにリサイズできる。 %>
        <% end %>

        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
              <%# 投稿に、サインインしているユーザーのいいねが、あるかどうかを判断する。 %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :post, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
            <%# <%= link_to "", "#", class: "love" %>
            <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <%# <div><strong>「いいね！」10件</strong></div> %>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
            
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
```

「link_to method: :post」で検索したところ、
いくつか記事が出てきたので、試してみましたがエラーになりました。

https://techracho.bpsinc.jp/hachi8833/2017_04_25/39061
link_to以降を()でまとめてみました。

https://www.javadrive.jp/rails/template/index8.html
post_likes_path(post)をpost_likes_path(@post)に変更しましたがダメでした。

もともとrails6で作ったアプリなので、
link_toの書き方もrails5では変わるのでしょうか。

**Comment by masayuki14** [comment]
> link_toの書き方もrails5では変わるのでしょうか。

https://railsdoc.com/page/link_to

マニュアルの適応バージョンを見る限りは変化はなさそうです。


該当部分の( link_to の）実際に出力されているHTMLはどのようになっていますか？

コンソールのRailsログで、何か出ていたりしますか？

**Comment by Kotaro18** [comment]
ご確認頂きまして、有難うございます。
また、HTMLやRailsのログを共有しておらず申し訳ございません。
現状は以下の通りになります。

HTMLのログ
<img width="1440" alt="HTMLの表示" src="https://user-images.githubusercontent.com/56097471/120248991-515ec800-c2b4-11eb-89ce-5cde2fa0bcdf.png">

Railsのログ
```
rails-rails3   | Started GET "/posts/2/likes" for 192.168.32.1 at 2021-05-31 23:40:09 +0000
rails-rails3   | Cannot render console from 192.168.32.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails-rails3   |    (19.8ms)  
rails-rails3   |        SELECT
rails-rails3   |                sqlite_version (*)
rails-rails3   |    (2.3ms)  
rails-rails3   |        SELECT
rails-rails3   |                "schema_migrations"."version"
rails-rails3   |        FROM
rails-rails3   |                "schema_migrations"
rails-rails3   |        ORDER BY
rails-rails3   |                "schema_migrations"."version" ASC
rails-rails3   |   
rails-rails3   | ActionController::RoutingError (No route matches [GET] "/posts/2/likes"):
```

やはりPOSTではなくGETで要求してしまっており、
RoutingErrorが出ています。

**Comment by Kotaro18** [comment]
いいねを押したら、GETを要求してしまうRoutingErrorについて、
引き続き調べていましたが、
いいね機能(likes)だけでなく、コメント機能(comments)もエラーが出ました。

コメント入力時
<img width="1440" alt="コメント入力時" src="https://user-images.githubusercontent.com/56097471/120402952-3ce70200-c37e-11eb-8a70-e7ec79b4145e.png">


コメントするときのエラー
<img width="1440" alt="コメントもエラー" src="https://user-images.githubusercontent.com/56097471/120402998-538d5900-c37e-11eb-89ba-847af0c8945c.png">

railsのログ
```
rails-rails3   | Started POST "/posts/2/comments" for 192.168.48.1 at 2021-06-01 23:51:30 +0000
rails-rails3   | Cannot render console from 192.168.48.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails-rails3   | Processing by CommentsController#create as HTML
rails-rails3   |   Parameters: 
rails-rails3   | {
rails-rails3   |     "authenticity_token" => "ww8AbmRE90C3t/d+Mh+yvwltcoLIe+eVibRoUEJ9GuF9hvaKgZ0RVMdMOs7H+4XTAyV5i7hhLamyQaFehzbn4g==",
rails-rails3   |                "comment" => {
rails-rails3   |         "user_id" => "1",
rails-rails3   |         "post_id" => "2",
rails-rails3   |         "comment" => "aaa"
rails-rails3   |     },
rails-rails3   |                "post_id" => "2"
rails-rails3   | }
rails-rails3   |   User Load (2.6ms)  
rails-rails3   |        SELECT
rails-rails3   |                "users" . *
rails-rails3   |        FROM
rails-rails3   |                "users"
rails-rails3   |        WHERE
rails-rails3   |                "users"."id" = ?
rails-rails3   |        ORDER BY
rails-rails3   |                "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   Post Load (8.8ms)  
rails-rails3   |        SELECT
rails-rails3   |                "posts" . *
rails-rails3   |        FROM
rails-rails3   |                "posts"
rails-rails3   |        WHERE
rails-rails3   |                "posts"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
rails-rails3   |   ↳ app/controllers/comments_controller.rb:7:in `create'
rails-rails3   |   TRANSACTION (0.1ms)  
rails-rails3   |        BEGIN TRANSACTION
rails-rails3   |   ↳ app/controllers/comments_controller.rb:8:in `create'
rails-rails3   |   User Load (4.6ms)  
rails-rails3   |        SELECT
rails-rails3   |                "users" . *
rails-rails3   |        FROM
rails-rails3   |                "users"
rails-rails3   |        WHERE
rails-rails3   |                "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   ↳ app/controllers/comments_controller.rb:8:in `create'
rails-rails3   |   Comment Create (23.7ms)  
rails-rails3   |        INSERT
rails-rails3   |        INTO
rails-rails3   |                "comments" (
rails-rails3   |                        "comment"
rails-rails3   |                        ,"post_id"
rails-rails3   |                        ,"user_id"
rails-rails3   |                        ,"created_at"
rails-rails3   |                        ,"updated_at"
rails-rails3   |                )
rails-rails3   |        VALUES (
rails-rails3   |                ?
rails-rails3   |                ,?
rails-rails3   |                ,?
rails-rails3   |                ,?
rails-rails3   |                ,?
rails-rails3   |        )  [["comment", "aaa"], ["post_id", 2], ["user_id", 1], ["created_at", "2021-06-01 23:51:30.344745"], ["updated_at", "2021-06-01 23:51:30.344745"]]
rails-rails3   |   ↳ app/controllers/comments_controller.rb:8:in `create'
rails-rails3   |   TRANSACTION (22.0ms)  
rails-rails3   |        COMMIT TRANSACTION
rails-rails3   |   ↳ app/controllers/comments_controller.rb:8:in `create'
rails-rails3   | Completed 406 Not Acceptable in 154ms (ActiveRecord: 61.8ms | Allocations: 37016)
rails-rails3   | 
rails-rails3   | 
rails-rails3   |   
rails-rails3   | ActionController::UnknownFormat (ActionController::UnknownFormat):
rails-rails3   |   
rails-rails3   | app/controllers/comments_controller.rb:9:in `create'
rails-rails3   | Started GET "/" for 192.168.48.1 at 2021-06-01 23:51:32 +0000
rails-rails3   | Cannot render console from 192.168.48.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails-rails3   | Processing by PostsController#index as HTML
rails-rails3   |   User Load (8.8ms)  
rails-rails3   |        SELECT
rails-rails3   |                "users" . *
rails-rails3   |        FROM
rails-rails3   |                "users"
rails-rails3   |        WHERE
rails-rails3   |                "users"."id" = ?
rails-rails3   |        ORDER BY
rails-rails3   |                "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   Rendering layout layouts/application.html.erb
rails-rails3   |   Rendering posts/index.html.erb within layouts/application
rails-rails3   |   Post Load (6.6ms)  
rails-rails3   |        SELECT
rails-rails3   |                "posts" . *
rails-rails3   |        FROM
rails-rails3   |                "posts"
rails-rails3   |        ORDER BY
rails-rails3   |                created_at DESC LIMIT ?  [["LIMIT", 10]]
rails-rails3   |   ↳ app/views/posts/index.html.erb:1
rails-rails3   |   Photo Load (5.4ms)  
rails-rails3   |        SELECT
rails-rails3   |                "photos" . *
rails-rails3   |        FROM
rails-rails3   |                "photos"
rails-rails3   |        WHERE
rails-rails3   |                "photos"."post_id" IN (
rails-rails3   |                        ?
rails-rails3   |                        ,?
rails-rails3   |                )  [[nil, 2], [nil, 1]]
rails-rails3   |   ↳ app/views/posts/index.html.erb:1
rails-rails3   |   User Load (2.8ms)  
rails-rails3   |        SELECT
rails-rails3   |                "users" . *
rails-rails3   |        FROM
rails-rails3   |                "users"
rails-rails3   |        WHERE
rails-rails3   |                "users"."id" = ?  [["id", 1]]
rails-rails3   |   ↳ app/views/posts/index.html.erb:1
rails-rails3   |   Like Load (4.6ms)  
rails-rails3   |        SELECT
rails-rails3   |                "likes" . *
rails-rails3   |        FROM
rails-rails3   |                "likes"
rails-rails3   |        WHERE
rails-rails3   |                "likes"."user_id" = ?
rails-rails3   |                AND "likes"."post_id" = ? LIMIT ?  [["user_id", 1], ["post_id", 2], ["LIMIT", 1]]
rails-rails3   |   ↳ app/models/post.rb:13:in `liked_by'
rails-rails3   |   Like Load (7.3ms)  
rails-rails3   |        SELECT
rails-rails3   |                "likes" . *
rails-rails3   |        FROM
rails-rails3   |                "likes"
rails-rails3   |        WHERE
rails-rails3   |                "likes"."post_id" = ?
rails-rails3   |        ORDER BY
rails-rails3   |                "likes"."created_at" DESC  [["post_id", 2]]
rails-rails3   |   ↳ app/views/posts/_like_text.html.erb:2
rails-rails3   |   Rendered posts/_like_text.html.erb (Duration: 20.7ms | Allocations: 7684)
rails-rails3   |   Comment Load (3.3ms)  
rails-rails3   |        SELECT
rails-rails3   |                "comments" . *
rails-rails3   |        FROM
rails-rails3   |                "comments"
rails-rails3   |        WHERE
rails-rails3   |                "comments"."post_id" = ?  [["post_id", 2]]
rails-rails3   |   ↳ app/views/posts/_comment_list.html.erb:1
rails-rails3   |   User Load (6.3ms)  
rails-rails3   |        SELECT
rails-rails3   |                "users" . *
rails-rails3   |        FROM
rails-rails3   |                "users"
rails-rails3   |        WHERE
rails-rails3   |                "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   ↳ app/views/posts/_comment_list.html.erb:3
rails-rails3   |   CACHE User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   ↳ app/views/posts/_comment_list.html.erb:3
rails-rails3   |   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
rails-rails3   |   ↳ app/views/posts/_comment_list.html.erb:3
rails-rails3   |   Rendered posts/_comment_list.html.erb (Duration: 60.7ms | Allocations: 12616)
rails-rails3   |   Like Load (4.2ms)  
rails-rails3   |        SELECT
rails-rails3   |                "likes" . *
rails-rails3   |        FROM
rails-rails3   |                "likes"
rails-rails3   |        WHERE
rails-rails3   |                "likes"."user_id" = ?
rails-rails3   |                AND "likes"."post_id" = ? LIMIT ?  [["user_id", 1], ["post_id", 1], ["LIMIT", 1]]
rails-rails3   |   ↳ app/models/post.rb:13:in `liked_by'
rails-rails3   |   Like Load (4.8ms)  
rails-rails3   |        SELECT
rails-rails3   |                "likes" . *
rails-rails3   |        FROM
rails-rails3   |                "likes"
rails-rails3   |        WHERE
rails-rails3   |                "likes"."post_id" = ?
rails-rails3   |        ORDER BY
rails-rails3   |                "likes"."created_at" DESC  [["post_id", 1]]
rails-rails3   |   ↳ app/views/posts/_like_text.html.erb:2
rails-rails3   |   Rendered posts/_like_text.html.erb (Duration: 19.4ms | Allocations: 7683)
rails-rails3   |   Comment Load (6.7ms)  
rails-rails3   |        SELECT
rails-rails3   |                "comments" . *
rails-rails3   |        FROM
rails-rails3   |                "comments"
rails-rails3   |        WHERE
rails-rails3   |                "comments"."post_id" = ?  [["post_id", 1]]
rails-rails3   |   ↳ app/views/posts/_comment_list.html.erb:1
rails-rails3   |   Rendered posts/_comment_list.html.erb (Duration: 18.0ms | Allocations: 5206)
rails-rails3   |   Rendered posts/index.html.erb within layouts/application (Duration: 230.5ms | Allocations: 68003)
rails-rails3   |   Rendered partial/_navbar.html.erb (Duration: 0.4ms | Allocations: 75)
rails-rails3   |   Rendered partial/_footer.html.erb (Duration: 0.1ms | Allocations: 5)
rails-rails3   |   Rendered layout layouts/application.html.erb (Duration: 362.7ms | Allocations: 78800)
rails-rails3   | Completed 200 OK in 407ms (Views: 325.8ms | ActiveRecord: 61.1ms | Allocations: 87764)
rails-rails3   | 
rails-rails3   | 
```

しかし何故か、エラーの後ブラウザバックすると、
コメントが反映されています。
<img width="1440" alt="コメント反映" src="https://user-images.githubusercontent.com/56097471/120403915-29d53180-c380-11eb-873e-acba0966fa24.png">


いいねのエラーについて調べていると、
「method: :deleteはjsが働いていないと適切に動かない」とありました。
今回はpostのエラーなので、直接関係しているかは分かりません。

コメントのエラーでも、
respond_to :jsの箇所でエラーが出ていますが、
javascriptsが正常に機能していないことが原因でしょうか。

**Comment by masayuki14** [comment]
`link_to` で出力されているHTMLは正常に出力されているようです。
こちらですね。
```html
<a class="love hide-text" data-remote="true" rel="nofollow" data-method="post" href="/posts/2/likes">いいね</a>
```

そもそも `<a>` たぐのリンクではGETリクエストしか送信できません。
Javascriptを使ってPOSTやDELETEメソッドでのリクエストを送信しています。

今回はおそらくJavascriptが正常に機能していないと思われます。
NetworksタブでJavascriptの読み込みにエラーが発生したりしていないでしょうか？

**Comment by masayuki14** [comment]
`application.debug.js` でエラーがでてますね。これを解消しましょう。

**Comment by Kotaro18** [comment]
ご確認頂き、有難うございます。

検証モードのNetwork
<img width="1440" alt="networkタブ1" src="https://user-images.githubusercontent.com/56097471/120561601-c90d2e00-c43f-11eb-999f-c8549b71805a.png">

仰る通り、```application.debug.js```で
Uncaught SyntaxError: Cannot use import statement outside a module
というエラーが出ています。

こちらを調べてみたいと思います。

**Comment by Kotaro18** [comment]
以下の記事を参照してみました。

https://inside.pixiv.blog/subal/4615
webpackerを剥がした際、代わりに必要になる、
```webpack.config.js```を作成していませんでした。

それが原因ではないかと思い、
https://qiita.com/one-kelvin/items/b810aafb6b5ef90789a3
上記の記事を参考に、デフォルトの```webpack.config.js```を作成しました。

webpack.config.js
```javascripts:webpack.config.js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const webpack = require('webpack')

module.exports = {
  entry: path.resolve(__dirname, "entry.js"),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      { test: /\.txt$/, use: 'raw-loader' }
    ]
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin(),
    new HtmlWebpackPlugin({ template: './src/index.html' })
  ]
}
```

この辺りの修正は必要なのではないかと思っています。

**Comment by Kotaro18** [comment]
また、こちらの記事にある様に、
https://numb86-tech.hatenablog.com/entry/2020/08/12/075048

```script type="module"```の設定ができていないのか、
またどこに記述するべきなのか理解できておりません。

**Comment by masayuki14** [comment]
ブラウザのエラーメッセージから実際のエラーが発生しているJavascriptのコードへ飛べますが、
そちらは確認していますか？
 `application.debug.js` はアセットパイプラインにより作成されるJavascriptファイルなので、
そのあたりにエラーの原因だとはあると思います。

**Comment by masayuki14** [comment]
まずはエラー発生箇所のソースコードがどこにあるかを探してください。

**Comment by Kotaro18** [comment]
ご確認頂きまして、有難うございます。

application.debug.jsを検索してみましたが、
記事が何も出てきません。
ブラウザの検証画面で名前が変わる仕様で、
元のファイルはapplication.jsとかなのでしょうか。

エラー部分から、consumer.jsをいうファイルを発見しました。
今まで見過ごしていただけですが。
<img width="1440" alt="consumer" src="https://user-images.githubusercontent.com/56097471/120943133-03403d80-c768-11eb-81df-c39995305429.png">

こちらについて公式ガイド等で調べてみました。
https://railsguides.jp/action_cable_overview.html
https://qiita.com/yokoto/items/fb1e66844b70f52682dd

こちらのサイトが分かりやすかったのですが、
https://docs.koheitakahashi.com/entry/2020/08/20/124333
```app/javascript/channels/timelines_channel.js```の様に、
受けとなるファイルがありませんでした。

現行では、 assets/javascripts内には、
```consumer.js```と```index.js```しかありません。

consumer.js
```javascript:consumer.js
// Action Cable provides the framework to deal with WebSockets in Rails.
// You can generate new channels where WebSocket features live using the `rails generate channel` command.

import { createConsumer } from "@rails/actioncable"

export default createConsumer()
```

index.js
```javascript:index.js
// Load all the channels within this directory and all subdirectories.
// Channel files must be named *_channel.js.

const channels = require.context('.', true, /_channel\.js$/)
channels.keys().forEach(channels)
```

**Comment by masayuki14** [comment]
エラーの発生箇所をブラウザで確認すると以下のようになっています。

`import`の行で `application.debug.js:22567 Uncaught SyntaxError: Cannot use import statement outside a module` とエラーが出ています。
import によるモジュールインポートは構文エラーということですね。

```
// Action Cable provides the framework to deal with WebSockets in Rails.
// You can generate new channels where WebSocket features live using the `rails generate channel` command.

import { createConsumer } from "@rails/actioncable"

export default createConsumer();
// Load all the channels within this directory and all subdirectories.
// Channel files must be named *_channel.js.
```
これは、こちらのふぁいるです。
https://github.com/Kotaro18/footomo/blob/master/app/assets/javascript/channels/consumer.js

と、ここまで調査しましたが、原因がいまいちわからないですね。
このファイルの構文エラーが本質的な原因だとはおもえないからです。

---

現状のRailsのバージョンが6なので、JavascriptやCSSはwebpackerを利用する前提となっています。

Rails 5 だとアセットパイプラインを使うので `app/assets/javascript/application.js` では `import` 構文は使いません。
ブラウザでは `import` 構文を使えないと思ってもらっていよいです。

以前、Rails５->６に変えたことにより、webpacker用の記述になっていませんか？

とりあえずrails5のデフォルトは以下なので

```
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file. JavaScript code in this file should be added after the last require_* statement.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```


---


`app/assets/javascript` いかのファイルがどの様な意図で設置されているかわかりませんが、
とりあえず以下のファイルの `import` や `requiere` といった nodejs 用の構文をコメントアウトすると動くようになります。

https://github.com/Kotaro18/footomo/blob/master/app/assets/javascript/channels/consumer.js
https://github.com/Kotaro18/footomo/blob/master/app/assets/javascript/channels/index.js
https://github.com/Kotaro18/footomo/blob/master/app/assets/javascript/application.js

**Comment by Kotaro18** [comment]
ご確認頂きまして、有難うございます。
Masaさんのご指示通りにコメントアウトしたところ、
いいねができいる様になりました。

<img width="1440" alt="いいね" src="https://user-images.githubusercontent.com/56097471/121277834-64a11180-c90c-11eb-8e47-af00d6cd72c7.png">

このアプリはもともとrails6で作成しているのですが、
webpackerを外したとき、他にも修正しないといけなかったのかもしれません。

rails5のアセットパイプラインでの、
javascriptの配置やデフォルトファイルを確認してみたいと思います。
有難うございます。

**Comment by Kotaro18** [comment]
rails5のjavascript
デフォルト設定
https://qiita.com/prgseek/items/bf77c44189c55a7b41d8
